- name: Install Docker using official Docker script
  hosts: web
  become: yes

  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download Docker installation script
      get_url:
        url: https://get.docker.com
        dest: /tmp/get-docker.sh
        mode: '0755'

    - name: Run Docker installation script
      command: sh /tmp/get-docker.sh

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Copy Flask app to remote server
      copy:
        src: ./app/
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
        mode: 0755

    - name: Build Docker image
      community.docker.docker_image:
        name: ansibleapp
        source: build
        build:
          path: /home/ubuntu/app

    - name: Run Docker container
      community.docker.docker_container:
        name: ansibleapp
        image: ansibleapp
        ports:
          - "5000:5000"

